// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2lwTxf34g2S5db0lxzMF8W8EYNQoe4w',
    appId: '1:292395954163:web:887233001d2a26b07bec86',
    messagingSenderId: '292395954163',
    projectId: 'falcon-9a536',
    authDomain: 'falcon-9a536.firebaseapp.com',
    storageBucket: 'falcon-9a536.firebasestorage.app',
    measurementId: 'G-NYP5NKKDCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYIIH7ZOiXofDEne6On-dqdfp4cCG5ZI',
    appId: '1:292395954163:android:c9899f1cde6a20aa7bec86',
    messagingSenderId: '292395954163',
    projectId: 'falcon-9a536',
    storageBucket: 'falcon-9a536.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvdX6kklru_HjlxIMy0TkCzwq7LZqQoTI',
    appId: '1:292395954163:ios:6b186141360a99a57bec86',
    messagingSenderId: '292395954163',
    projectId: 'falcon-9a536',
    storageBucket: 'falcon-9a536.firebasestorage.app',
    iosBundleId: 'com.lumko.ifalcontraceapp',
  );
}
